//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.14 at 02:43:46 PM ICT 
//


package etda.uncefact.data.standard.debitcreditnote_reusableaggregatebusinessinformationentity._2;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the etda.uncefact.data.standard.debitcreditnote_reusableaggregatebusinessinformationentity._2 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _SupplyChainTradeTransaction_QNAME = new QName("urn:etda:uncefact:data:standard:DebitCreditNote_ReusableAggregateBusinessInformationEntity:2", "SupplyChainTradeTransaction");
    private final static QName _DocumentContextParameter_QNAME = new QName("urn:etda:uncefact:data:standard:DebitCreditNote_ReusableAggregateBusinessInformationEntity:2", "DocumentContextParameter");
    private final static QName _ExchangedDocument_QNAME = new QName("urn:etda:uncefact:data:standard:DebitCreditNote_ReusableAggregateBusinessInformationEntity:2", "ExchangedDocument");
    private final static QName _ExchangedDocumentContext_QNAME = new QName("urn:etda:uncefact:data:standard:DebitCreditNote_ReusableAggregateBusinessInformationEntity:2", "ExchangedDocumentContext");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: etda.uncefact.data.standard.debitcreditnote_reusableaggregatebusinessinformationentity._2
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DocumentContextParameterType }
     * 
     */
    public DocumentContextParameterType createDocumentContextParameterType() {
        return new DocumentContextParameterType();
    }

    /**
     * Create an instance of {@link ExchangedDocumentContextType }
     * 
     */
    public ExchangedDocumentContextType createExchangedDocumentContextType() {
        return new ExchangedDocumentContextType();
    }

    /**
     * Create an instance of {@link ExchangedDocumentType }
     * 
     */
    public ExchangedDocumentType createExchangedDocumentType() {
        return new ExchangedDocumentType();
    }

    /**
     * Create an instance of {@link SupplyChainTradeTransactionType }
     * 
     */
    public SupplyChainTradeTransactionType createSupplyChainTradeTransactionType() {
        return new SupplyChainTradeTransactionType();
    }

    /**
     * Create an instance of {@link CIUniversalCommunicationType }
     * 
     */
    public CIUniversalCommunicationType createCIUniversalCommunicationType() {
        return new CIUniversalCommunicationType();
    }

    /**
     * Create an instance of {@link TradePriceType }
     * 
     */
    public TradePriceType createTradePriceType() {
        return new TradePriceType();
    }

    /**
     * Create an instance of {@link TradeProductType }
     * 
     */
    public TradeProductType createTradeProductType() {
        return new TradeProductType();
    }

    /**
     * Create an instance of {@link HeaderTradeAgreementType }
     * 
     */
    public HeaderTradeAgreementType createHeaderTradeAgreementType() {
        return new HeaderTradeAgreementType();
    }

    /**
     * Create an instance of {@link SupplyChainTradeLineItemType }
     * 
     */
    public SupplyChainTradeLineItemType createSupplyChainTradeLineItemType() {
        return new SupplyChainTradeLineItemType();
    }

    /**
     * Create an instance of {@link TradePaymentTermsType }
     * 
     */
    public TradePaymentTermsType createTradePaymentTermsType() {
        return new TradePaymentTermsType();
    }

    /**
     * Create an instance of {@link HeaderTradeDeliveryType }
     * 
     */
    public HeaderTradeDeliveryType createHeaderTradeDeliveryType() {
        return new HeaderTradeDeliveryType();
    }

    /**
     * Create an instance of {@link LineTradeSettlementType }
     * 
     */
    public LineTradeSettlementType createLineTradeSettlementType() {
        return new LineTradeSettlementType();
    }

    /**
     * Create an instance of {@link TradeCountryType }
     * 
     */
    public TradeCountryType createTradeCountryType() {
        return new TradeCountryType();
    }

    /**
     * Create an instance of {@link HeaderTradeSettlementType }
     * 
     */
    public HeaderTradeSettlementType createHeaderTradeSettlementType() {
        return new HeaderTradeSettlementType();
    }

    /**
     * Create an instance of {@link TradeAllowanceChargeType }
     * 
     */
    public TradeAllowanceChargeType createTradeAllowanceChargeType() {
        return new TradeAllowanceChargeType();
    }

    /**
     * Create an instance of {@link EmailUniversalCommunicationType }
     * 
     */
    public EmailUniversalCommunicationType createEmailUniversalCommunicationType() {
        return new EmailUniversalCommunicationType();
    }

    /**
     * Create an instance of {@link TradeDeliveryTermsType }
     * 
     */
    public TradeDeliveryTermsType createTradeDeliveryTermsType() {
        return new TradeDeliveryTermsType();
    }

    /**
     * Create an instance of {@link TelephoneUniversalCommunicationType }
     * 
     */
    public TelephoneUniversalCommunicationType createTelephoneUniversalCommunicationType() {
        return new TelephoneUniversalCommunicationType();
    }

    /**
     * Create an instance of {@link LineSettlementMonetarySummationType }
     * 
     */
    public LineSettlementMonetarySummationType createLineSettlementMonetarySummationType() {
        return new LineSettlementMonetarySummationType();
    }

    /**
     * Create an instance of {@link TradeAddressType }
     * 
     */
    public TradeAddressType createTradeAddressType() {
        return new TradeAddressType();
    }

    /**
     * Create an instance of {@link SpecifiedTaxRegistrationType }
     * 
     */
    public SpecifiedTaxRegistrationType createSpecifiedTaxRegistrationType() {
        return new SpecifiedTaxRegistrationType();
    }

    /**
     * Create an instance of {@link SupplyChainEventType }
     * 
     */
    public SupplyChainEventType createSupplyChainEventType() {
        return new SupplyChainEventType();
    }

    /**
     * Create an instance of {@link TradePartyType }
     * 
     */
    public TradePartyType createTradePartyType() {
        return new TradePartyType();
    }

    /**
     * Create an instance of {@link LineTradeAgreementType }
     * 
     */
    public LineTradeAgreementType createLineTradeAgreementType() {
        return new LineTradeAgreementType();
    }

    /**
     * Create an instance of {@link ProductClassificationType }
     * 
     */
    public ProductClassificationType createProductClassificationType() {
        return new ProductClassificationType();
    }

    /**
     * Create an instance of {@link TradeContactType }
     * 
     */
    public TradeContactType createTradeContactType() {
        return new TradeContactType();
    }

    /**
     * Create an instance of {@link TradeProductInstanceType }
     * 
     */
    public TradeProductInstanceType createTradeProductInstanceType() {
        return new TradeProductInstanceType();
    }

    /**
     * Create an instance of {@link NoteType }
     * 
     */
    public NoteType createNoteType() {
        return new NoteType();
    }

    /**
     * Create an instance of {@link LineTradeDeliveryType }
     * 
     */
    public LineTradeDeliveryType createLineTradeDeliveryType() {
        return new LineTradeDeliveryType();
    }

    /**
     * Create an instance of {@link TradeSettlementMonetaryHeaderSummationType }
     * 
     */
    public TradeSettlementMonetaryHeaderSummationType createTradeSettlementMonetaryHeaderSummationType() {
        return new TradeSettlementMonetaryHeaderSummationType();
    }

    /**
     * Create an instance of {@link TradeTaxType }
     * 
     */
    public TradeTaxType createTradeTaxType() {
        return new TradeTaxType();
    }

    /**
     * Create an instance of {@link ReferencedDocumentType }
     * 
     */
    public ReferencedDocumentType createReferencedDocumentType() {
        return new ReferencedDocumentType();
    }

    /**
     * Create an instance of {@link DocumentLineDocumentType }
     * 
     */
    public DocumentLineDocumentType createDocumentLineDocumentType() {
        return new DocumentLineDocumentType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SupplyChainTradeTransactionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:etda:uncefact:data:standard:DebitCreditNote_ReusableAggregateBusinessInformationEntity:2", name = "SupplyChainTradeTransaction")
    public JAXBElement<SupplyChainTradeTransactionType> createSupplyChainTradeTransaction(SupplyChainTradeTransactionType value) {
        return new JAXBElement<SupplyChainTradeTransactionType>(_SupplyChainTradeTransaction_QNAME, SupplyChainTradeTransactionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DocumentContextParameterType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:etda:uncefact:data:standard:DebitCreditNote_ReusableAggregateBusinessInformationEntity:2", name = "DocumentContextParameter")
    public JAXBElement<DocumentContextParameterType> createDocumentContextParameter(DocumentContextParameterType value) {
        return new JAXBElement<DocumentContextParameterType>(_DocumentContextParameter_QNAME, DocumentContextParameterType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExchangedDocumentType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:etda:uncefact:data:standard:DebitCreditNote_ReusableAggregateBusinessInformationEntity:2", name = "ExchangedDocument")
    public JAXBElement<ExchangedDocumentType> createExchangedDocument(ExchangedDocumentType value) {
        return new JAXBElement<ExchangedDocumentType>(_ExchangedDocument_QNAME, ExchangedDocumentType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExchangedDocumentContextType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:etda:uncefact:data:standard:DebitCreditNote_ReusableAggregateBusinessInformationEntity:2", name = "ExchangedDocumentContext")
    public JAXBElement<ExchangedDocumentContextType> createExchangedDocumentContext(ExchangedDocumentContextType value) {
        return new JAXBElement<ExchangedDocumentContextType>(_ExchangedDocumentContext_QNAME, ExchangedDocumentContextType.class, null, value);
    }

}
