//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.14 at 02:43:46 PM ICT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:etda:uncefact:data:standard:DebitCreditNote_ReusableAggregateBusinessInformationEntity:2", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package etda.uncefact.data.standard.debitcreditnote_reusableaggregatebusinessinformationentity._2;
