//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.14 at 02:43:46 PM ICT 
//


package etda.uncefact.data.standard.qualifieddatatype._1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import un.unece.uncefact.codelist.standard.unece.allowancechargereasoncode.d15b.AllowanceChargeReasonCodeContentType;


/**
 * <p>Java class for AllowanceChargeReasonCode complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AllowanceChargeReasonCode">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;urn:un:unece:uncefact:codelist:standard:UNECE:AllowanceChargeReasonCode:D15B>AllowanceChargeReasonCodeContentType">
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AllowanceChargeReasonCode", propOrder = {
    "value"
})
public class AllowanceChargeReasonCode {

    @XmlValue
    protected AllowanceChargeReasonCodeContentType value;

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link AllowanceChargeReasonCodeContentType }
     *     
     */
    public AllowanceChargeReasonCodeContentType getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link AllowanceChargeReasonCodeContentType }
     *     
     */
    public void setValue(AllowanceChargeReasonCodeContentType value) {
        this.value = value;
    }

}
