//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.14 at 02:43:46 PM ICT 
//


package etda.uncefact.codelist.standard.thaimessagefunctioncode._1;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ThaiMessageFunctionCodeContentType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ThaiMessageFunctionCodeContentType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="80"/>
 *     &lt;enumeration value="81"/>
 *     &lt;enumeration value="82"/>
 *     &lt;enumeration value="380"/>
 *     &lt;enumeration value="388"/>
 *     &lt;enumeration value="T01"/>
 *     &lt;enumeration value="T02"/>
 *     &lt;enumeration value="T03"/>
 *     &lt;enumeration value="T04"/>
 *     &lt;enumeration value="T05"/>
 *     &lt;enumeration value="T06"/>
 *     &lt;enumeration value="T07"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ThaiMessageFunctionCodeContentType", namespace = "urn:etda:uncefact:codelist:standard:ThaiMessageFunctionCode:1")
@XmlEnum
public enum ThaiMessageFunctionCodeContentType {


    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:Name xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2" xmlns:thaiclm61001Invoice="urn:etda:uncefact:codelist:standard:ThaiMessageFunctionCode:1" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;Debit note related to goods or services&lt;/ccts:Name&gt;
     * </pre>
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:Description xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2" xmlns:thaiclm61001Invoice="urn:etda:uncefact:codelist:standard:ThaiMessageFunctionCode:1" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;Debit information related to a transaction for goods or services to the relevant party.&lt;/ccts:Description&gt;
     * </pre>
     * 
     * 
     */
    @XmlEnumValue("80")
    VALUE_1("80"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:Name xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2" xmlns:thaiclm61001Invoice="urn:etda:uncefact:codelist:standard:ThaiMessageFunctionCode:1" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;Credit note related to goods or services&lt;/ccts:Name&gt;
     * </pre>
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:Description xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2" xmlns:thaiclm61001Invoice="urn:etda:uncefact:codelist:standard:ThaiMessageFunctionCode:1" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;Document message used to provide credit information related to a transaction for goods or services to the relevant party.&lt;/ccts:Description&gt;
     * </pre>
     * 
     * 
     */
    @XmlEnumValue("81")
    VALUE_2("81"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:Name xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2" xmlns:thaiclm61001Invoice="urn:etda:uncefact:codelist:standard:ThaiMessageFunctionCode:1" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;Metered services invoice&lt;/ccts:Name&gt;
     * </pre>
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:Description xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2" xmlns:thaiclm61001Invoice="urn:etda:uncefact:codelist:standard:ThaiMessageFunctionCode:1" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;Document/message claiming payment for the supply of metered services (e.g., gas, electricity, etc.) supplied to a fixed meter whose consumption is measured over a period of time.&lt;/ccts:Description&gt;
     * </pre>
     * 
     * 
     */
    @XmlEnumValue("82")
    VALUE_3("82"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:Name xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2" xmlns:thaiclm61001Invoice="urn:etda:uncefact:codelist:standard:ThaiMessageFunctionCode:1" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;Commercial invoice&lt;/ccts:Name&gt;
     * </pre>
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:Description xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2" xmlns:thaiclm61001Invoice="urn:etda:uncefact:codelist:standard:ThaiMessageFunctionCode:1" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;(1334) Document/message claiming payment for goods or services supplied under conditions agreed between seller and buyer.&lt;/ccts:Description&gt;
     * </pre>
     * 
     * 
     */
    @XmlEnumValue("380")
    VALUE_4("380"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:Name xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2" xmlns:thaiclm61001Invoice="urn:etda:uncefact:codelist:standard:ThaiMessageFunctionCode:1" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;Self-billed invoice&lt;/ccts:Name&gt;
     * </pre>
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:Description xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2" xmlns:thaiclm61001Invoice="urn:etda:uncefact:codelist:standard:ThaiMessageFunctionCode:1" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;An invoice the invoicee is producing instead of the seller.&lt;/ccts:Description&gt;
     * </pre>
     * 
     * 
     */
    @XmlEnumValue("388")
    VALUE_5("388"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:Name xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2" xmlns:thaiclm61001Invoice="urn:etda:uncefact:codelist:standard:ThaiMessageFunctionCode:1" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;Consignment invoice&lt;/ccts:Name&gt;
     * </pre>
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:Description xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2" xmlns:thaiclm61001Invoice="urn:etda:uncefact:codelist:standard:ThaiMessageFunctionCode:1" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;Commercial invoice that covers a transaction other than one involving a sale.&lt;/ccts:Description&gt;
     * </pre>
     * 
     * 
     */
    @XmlEnumValue("T01")
    VALUE_6("T01"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:Name xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2" xmlns:thaiclm61001Invoice="urn:etda:uncefact:codelist:standard:ThaiMessageFunctionCode:1" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;Factored credit note&lt;/ccts:Name&gt;
     * </pre>
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:Description xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2" xmlns:thaiclm61001Invoice="urn:etda:uncefact:codelist:standard:ThaiMessageFunctionCode:1" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;Credit note related to assigned invoice(s).&lt;/ccts:Description&gt;
     * </pre>
     * 
     * 
     */
    @XmlEnumValue("T02")
    VALUE_7("T02"),
    @XmlEnumValue("T03")
    VALUE_8("T03"),
    @XmlEnumValue("T04")
    VALUE_9("T04"),
    @XmlEnumValue("T05")
    VALUE_10("T05"),
    @XmlEnumValue("T06")
    VALUE_11("T06"),
    @XmlEnumValue("T07")
    VALUE_12("T07");
    private final String value;

    ThaiMessageFunctionCodeContentType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ThaiMessageFunctionCodeContentType fromValue(String v) {
        for (ThaiMessageFunctionCodeContentType c: ThaiMessageFunctionCodeContentType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
